# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "企业版"
  lane :enterprise do
gym(
      scheme: "YaSha-iOS",
      export_method: "enterprise",
      configuration: "Debug",
      output_directory: "/Users/gongshouhui/Desktop/build",
      include_bitcode: false
      )

    # add actions here: https://docs.fastlane.tools/actions
  end
end
